### ISSUE TITLE
Infografía de los Sistemas Numéricos 

### ISSUE THREAD

**Issue by Maritza2893** [SistemasTecTlaxiaco/infografia-Maritza2893#2]
[sistemas numericos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Maritza2893/files/12502176/sistemas.numericos.pdf)

**Comment by elisa1223** [comment]
Redaccion     10%
Expresion de ideas    15%
Organizacion de la informacion    15%
Uso de imagenes    15%
Presentación visual    13%
Referencias     15%
Presentación    13%

Calicacion :    19/20
Evaluado por: Elisa Sánchez Coronel

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
